services:
  services:
    postgres:
      image: postgres:16.4
      container_name: ada_bank_api_postgres
      restart: unless-stopped
      environment:
        POSTGRES_DB: biblioteca_api
        POSTGRES_USER: bibliotecario.admin
        POSTGRES_PASSWORD: marcrisanna
      ports:
        - "5432:5432"
      volumes:
        - ./init:/docker-entrypoint-initdb.d:ro
        - biblioteca_api_data:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ada.tech -d 'ada_bank_api'" ]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 30s

  volumes:
    biblioteca_api_data:

  # ------------------------------------------------------------
  # Como usar:
  #   docker compose up -d
  #
  # Aguarde o container ficar healthy e então suba a aplicação:
  #   ./mvnw quarkus:dev
  #
  # application.properties (Quarkus):
  #   quarkus.datasource.db-kind=postgresql
  #   quarkus.datasource.username=ada.tech
  #   quarkus.datasource.password=turma1660
  #   quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ada_bank_api
  #   quarkus.hibernate-orm.database.generation=none
  # ------------------------------------------------------------