quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=bibliotecario.admin
quarkus.datasource.password=marcrisanna
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/biblioteca_api
quarkus.hibernate-orm.database.generation=create
quarkus.hibernate-orm.log.sql=true