# ---------- Comum a todos os ambientes ----------
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${APP_DB_USER}
quarkus.datasource.password=${APP_DB_PASSWORD}
quarkus.hibernate-orm.log.sql=true

# Prefixo global da API REST
quarkus.rest.path=/api

# ---------- Perfil dev (ambiente local) ----------
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/biblioteca_api
%dev.quarkus.hibernate-orm.database.generation=update

# ---------- Perfil prod (VPS) ----------
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/biblioteca_api
%prod.quarkus.hibernate-orm.database.generation=update